name: llmscope-phase5

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: llmscope_api
    env_file:
      - ./docker/.env
    environment:
      # Force DB path inside a volume
      - DATABASE_PATH=/data/llmscope.db
      - LLMSCOPE_API_KEY=${LLMSCOPE_API_KEY}
      - DATA_RETENTION_DAYS=${DATA_RETENTION_DAYS}
    volumes:
      - ../data:/data
      - ../backend:/app/backend:ro
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/api/providers || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  web:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: llmscope_web
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: unless-stopped

  monitor:
    build:
      context: ..
      dockerfile: docker/Dockerfile.monitor
    container_name: llmscope_monitor
    depends_on:
      api:
        condition: service_healthy
    env_file:
      - ./docker/.env
    environment:
      - LLMSCOPE_API_KEY=${LLMSCOPE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OLLAMA_URL=${OLLAMA_URL}
      - MONITORING_INTERVAL=${MONITORING_INTERVAL}
      # Let monitor post to backend directly inside the network
      - LLMSCOPE_BASE=http://api:8000
    restart: unless-stopped

volumes: {}
      # Using bind mount ../data instead of named volume for easy inspection
      # Uncomment if you prefer named volume
      # llmscope_data:
