New-Item -ItemType Directory -Force -Path .github\workflows | Out-Null
@'
name: Nightly Release

on:
  schedule:
    - cron: "10 7 * * *"   # 07:10 UTC = 03:10 ET
  workflow_dispatch:

permissions:
  contents: write

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install PowerShell (pwsh)
        uses: PowerShell/PowerShell@v1
        with:
          version: "7.4.1"

      - name: Git identity
        run: |
          git config user.name  "LLMscope Nightly Bot"
          git config user.email "actions@users.noreply.github.com"

      - name: Run nightly release script
        shell: pwsh
        run: ./scripts/release_nightly.ps1
'@ | Set-Content -Encoding UTF8 .github\workflows\nightly-release.yml
