name: Nightly Release

on:
  schedule:
    - cron: '10 7 * * *'  # 07:10 UTC = 03:10 ET
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "LLMscope Nightly Bot"
          git config user.email "actions@users.noreply.github.com"

      - name: Run nightly release script
        shell: pwsh
        run: ./scripts/release_nightly.ps1
